apiVersion: v1
kind: Secret
metadata:
  name: premier-league-etl-secrets
  namespace: default
type: Opaque
stringData:
  # API Keys
  API_SPORTS_KEY: "your_api_sports_key_here"
  API_FOOTBALL_KEY: "your_api_football_key_here"

  # Email Credentials
  ALERT_EMAIL: "your_email@gmail.com"
  EMAIL_PASSWORD: "your_gmail_app_password"

  # BigQuery Credentials (base64 encoded JSON)
  # To create: cat bigquery_credentials.json | base64 -w 0
  GOOGLE_APPLICATION_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "your-private-key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n",
      "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"
    }

---
# Note: In production, use kubectl to create secrets securely:
# kubectl create secret generic premier-league-etl-secrets \
#   --from-literal=API_SPORTS_KEY=your_key \
#   --from-literal=API_FOOTBALL_KEY=your_key \
#   --from-file=GOOGLE_APPLICATION_CREDENTIALS_JSON=./bigquery_credentials.json \
#   --from-literal=ALERT_EMAIL=your_email@gmail.com \
#   --from-literal=EMAIL_PASSWORD=your_password